# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True, verbose_name='Birth Date')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='person_profile/%Y/%m/', verbose_name='')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='UID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('F', 'Friend'), ('B', 'Break'), ('R', 'Reject')], default='F', max_length=1)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to='account.Profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_set',
            field=models.ManyToManyField(blank=True, through='account.Relation', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
