# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171225_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_published',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='status',
            new_name='public',
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.ImageField(upload_to='contents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Theme Name'),
        ),
    ]
