# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='viewed',
        ),
        migrations.AddField(
            model_name='friendshiprequest',
            name='rejected_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
