# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171225_1234'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Theme'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PL', 'Liked'), ('PC', 'Commented'), ('PC', 'Bucket'), ('TM', 'Theme')], max_length=2),
        ),
    ]
